name: chattogram
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase dependencies
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3

  # Image and video handling
  image_picker: ^1.0.4
  file_picker: ^8.0.7
  video_player: ^2.7.1
  chewie: ^1.8.3

  # Audio recording and playback
  flutter_sound: 9.11.2
  path_provider: ^2.1.4

  # State management and utilities
  provider: ^6.1.2

  # UI enhancements
  font_awesome_flutter: ^10.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  #assets:
    # Uncomment and add your assets here if you have any
    # - assets/images/
    # - assets/audios/
    # - assets/videos/
